#!/usr/bin/env bash
# the project file layout is a template clone of http://www.davekuhlman.org/generateDS.html#id14
# for which we run:
git branch -D generated_odoo
git checkout -b generated_odoo

SCHEMA_NAME='nfse'
python quick_start.py --schema-name="$SCHEMA_NAME"
export GENERATEDS_HOME=${GENERATEDS_HOME:="/home/rvalyi/DEV/generateds"}

generate() {
  local version=$1
  local schemas_url=$2
  local lib_name="$SCHEMA_NAME"lib
  local gen_path="$SCHEMA_NAME"lib/"$version"
  wget -qO- --no-check-certificate "$schemas_url" -O /tmp/schemas.zip
  rm -rf "schemas/$version"
  unzip /tmp/schemas.zip -d schemas/"$version"
  rm /tmp/schemas.zip
  mv schemas/"$version"/nfse*.txt schemas/"$version"/nfse.xsd
  sed -i 's/ xsd:/<xsd:/' schemas/"$version"/nfse.xsd # FIXES schema typo
  rm -rf __init__.py

  local module_contents=$(cat  <<EOF
Module contents
=================

EOF
)

  echo "$module_contents" > docs/module_contents.txt
  echo "sys.path.append(os.path.abspath('../$gen_path'))" >> docs/conf.py

  rm -rf $gen_path
  mkdir -p $gen_path
  local odoo_path=odoo/models/"$version"
  mkdir -p $odoo_path
  touch "$lib_name"/__init__.py
  touch "$gen_path/__init__.py"

  cp "schemas/$version"/*.xsd "$GENERATEDS_HOME"/odoo

  for f in "schemas/$version"/nf*.xsd;
  do
    echo "Processing $f file..";
    local name=$(echo "$f" | sed 's/\.xsd//g' | sed 's/\./_/g' | sed "s/_$version//g")
    local module_name=$(echo $name | tr "/" "\n" | tail -n1)
    python3 "$GENERATEDS_HOME"/generateDS.py -o "$gen_path/$module_name".py "$f"
    autopep8 --in-place -p3 "$gen_path/$module_name".py

local current_dir=$(pwd)

    cd "$GENERATEDS_HOME"/odoo
    cp ../generateDS.py .
    sed -i '/xmldsig-core-schema/d' nfse.xsd
    sed -i '/xsd:import namespace=\"http:\/\/www\.w3\.org\/2000\/09\/xmldsig/d' nfse.xsd
    ./gends_run_gen_odoo.py -f -v nfse.xsd
#    autopep8 --in-place -p3 models.py
    rm nfse.py
    mv models.py "$current_dir/$odoo_path"/nfse.py

cd "$current_dir"

    module_name=$(echo $name | tr "/" "\n" | tail -n1)
    module_contents_part=$(cat  <<EOF
.. automodule:: $module_name
    :members:
    :undoc-members:
    :show-inheritance:
EOF
)
    echo "$module_contents_part" >> docs/module_contents.txt

  done
  rm -f "$GENERATEDS_HOME"/odoo/*.xsd
  rm -f "$GENERATEDS_HOME"/odoo/*lib.py
}

generate "v2_03" "http://www.abrasf.org.br/arquivos/publico/NFS-e/Versao_2.03/schema_xml_nfs-e_%20v2.03.zip"


cd docs
make html
cd ..

rm -rf README.txt
rm -rf nfeutils.py
rm -rf sample_code

git add .
git commit . -m "classes and doc generated with ./generate"
